# Service Account under which the Porter Agent runs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-role
subjects:
  - kind: ServiceAccount
    name: agent
