name: Publish OLM Bundle

on:
  push:
    branches:
      - main
    paths:
      - 'porter/olm/**'
  pull_request:
    paths:
      - 'porter/olm/**'

jobs:
  publish:
    name: Publish OLM
    runs-on: ubuntu-latest
    steps:
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.3
      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Porter Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: porter publish